[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Backend for Anki Addon"
authors = ["Vlad"]

[tool.poetry.dependencies]
python = ">=3.13"
fastapi = "*"
uvicorn = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
