[project]
name = "anki-frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anki>=25.2.1",
    "aqt>=25.2.1",
    "doit>=0.36.0",
    "pyqt5>=5.15.11",
    "pytest>=8.3.5",
]
