[tool.poetry]
name = "anki-frontend"
version = "0.1.0"
description = "Anki Addon Frontend"
authors = ["Vlad"]

[tool.poetry.dependencies]
python = ">=3.13"
pyqt = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
